# -*- coding: utf-8 -*-
"""basis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CwlYV2MVr-tsRKRHKZsxRNM_wmuz79pb
"""

n = int(input("N: "))
k = int(input("K: "))

#x = []

sum = 0

for i in range(5):
  d = n / k
  m = n % k

  n = int(d)

  sum = sum + m
  x.append(int(m))

  print(int(d))
  print(int(m))

print(x)
#print(sum(x))
print(sum)

n = int(input("N: "))
k = int(input("K: "))

#x = []

sum = 0

while True:
  d = n / k
  m = n % k

  n = int(d)

  sum = sum + m
  x.append(int(m))

  if d == 0:
    break

  print(int(d))
  print(int(m))

print(x)
#print(sum(x))
print(sum)